<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $escaper Magento\Framework\Escaper */
/** @var $postVm TechDriven\Blog\ViewModel\Post*/
$postVm = $block->getData('post_vm');
$post = $postVm->getDetail();
?>
<div class="blog-post-detail">
    <h1><?= $escaper->escapeHtml($post->getTitle()); ?></h1>
    <p><em><?=__('Created at: %1', $post->getCreatedAt()) ?></em></p>
    <p><?= $escaper->escapeHtml($post->getContent(), ['em','p','strong']) ?></p>
</div>
